inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/bundle
    - db/schema.rb
    - db/migrate

Layout/LineLength:
  Exclude:
    - db/migrate/*
    - Gemfile
    - config/initializers/devise.rb

Lint/EmptyBlock:
  Exclude:
    - spec/requests/api/v1/sessions/destroy_spec.rb
    - spec/requests/api/v1/topics/index_spec.rb
    - spec/acceptance/topics_spec.rb

Rails/Delegate:
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/api/v1/api_controller.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Lint/UnusedMethodArgument:
  Exclude:
    - spec/support/devise_token_auth_overrides.rb  

Metrics/MethodLength:
  Exclude:
    - db/migrate/20220714174633_create_active_storage_tables.active_storage.rb
