FORMAT: 1A
# Target API

# Group Topics

## Index topics [/api/v1/topics]

### Index [GET]

+ Request Get all topics Success

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: ardith_welch@schaefer.biz

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: ardith_welch@schaefer.biz

    + Body

            {
              "topics": [
                {
                  "id": 4,
                  "name": "ut",
                  "image_url": "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2cd83a8b2fe3fe168b2a341b4ebaf69cbfb737bf/li_.png"
                },
                {
                  "id": 5,
                  "name": "modi",
                  "image_url": "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb9c858d263e3f9368c856be50080692767432f2/li_.png"
                },
                {
                  "id": 6,
                  "name": "assumenda",
                  "image_url": "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--933777951a67c9403201b9fa6bfc917217b9a5bc/li_.png"
                }
              ]
            }
