
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: target_development

test:
  <<: *default
  database: target_test

production:
  <<: *default
  database: target_production
  username: target
  password: <%= ENV["TARGET_DATABASE_PASSWORD"] %>
