SECRET_KEY_BASE:
SERVER_URL: 'localhost:3000'
PASSWORD_RESET_URL: 'http://127.0.0.1:3000'
AWS_ACCESS_KEY_ID:  'AKIASPKYDZ4OPNEYZDOO'
AWS_SECRET_ACCESS_KEY: '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'
S3_BUCKET_NAME: 'backend-target'
AWS_BUCKET_REGION: 'sa-east-1'
TARGET_API_TOKEN: 
TARGET_API_URL:
TARGET_ACCOUNT_ID:
PAGY_ITEM_NUMBER: '15'